#!/usr/bin/env ruby

# Kevin Mendoza
# CSCI 465
# Project 1

# Lines 8-10 are to test if ruby
# was installed correctly
# print "Enter a string: "
# a = gets.chomp
# print {a}

require 'find'              # Adds module "find"

extension   = Array.new     # Note: Same as extension = []
directory   = Dir.pwd       # Current Directory
regex       = ARGV[0].to_s  # Turns terminal input into a string (to_s)
fSearch     = Array.new
lineNum     = Array.new
count = 0

Find.find(directory) do |path|
    extension << path if path =~ /#{regex}\w*.rb\b/
    extension << path if path =~ /#{regex}\w*.erb\b/
    extension << path if path =~ /#{regex}\w*.js\b/
    extension << path if path =~ /#{regex}\w*.css\b/
    extension << path if path =~ /#{regex}\w*.html\b/
    extension << path if path =~ /#{regex}\w*.yml\b/
    extension << path if path =~ /#{regex}\w*.txt\b/
end

extension.each do |filename|
    File.open filename do |file|
        file.each_line {count += 1}
        fSearch << file.find {|line| line =~ /#{regex}/}
        #return count if fSearch =~ /#{regex}/
    end
end

puts "Files with names that matches <#{regex}>"
if extension.size > 0
    puts "  .#{extension.join("\n  .")}"
end

puts "**************************************************"
puts "Files with content that matches <#{regex}>"
if count > 0
    print "  #{count}:"
    puts fSearch
end
